### ISSUE TITLE
Types of debugging Technique.

### ISSUE THREAD

**Issue by jjTudu** [NativeScript/nativescript-marketplace-demo#179]
Please specify the different type of debugging process, catch process bottleneck or which IDE will be best for debugging.

**Comment by PanayotCankov** [comment]
VSCode is best for debugging at the moment. You can check the NativeScript here:
https://github.com/NativeScript/nativescript-vscode-extension

Bottleneck are bloated visual trees. In general try to achieve the best results with as fewer as possible GridLayoute and StackLayout instances.

Avoid using Repeater for lots of items. It does not use UI visualization. Try to stick to the ListView, it does visualize and recycle the UI.

Usually {N} is fast enough but frequently a lot of changes on the visual tree happen during animations that cause the animation to skip few frames now and then making the app appear "slow". Most of the issues can be resolved following a few very simple recomendations.
 1. Set bindingContext in navigatingTo that updates the UI before a Page intro is played. Otherwise if you set it on loaded or navigatedTo chances are the UI will update half the way through the animation.
 2. If your binding context will instantiate a lot of UI - set it in navigatedTo or postpone it a little with timeout, so tapping a navigation button can bring up the new page as soon as possible (without waiting for tons of UI to instantiate) and after the animation is played, set the bindingContext to populate any heavy template list views or repeaters after the animation has finished.
 3. If you are making http requests start them in navigatingTo so that you can get data ASAP. But don't set that data in the bindingContext before the navigatedTo is called or the intro animation has finished, so your UI don't get populated half through a page intro animation.
 4. If you use animations, don't modify the visual tree during the animation. Create all objects before the animations, animate translate, rotate, and if you have to show or hide something use opacity, set the visibility when all animations complete.

probably this is not extensive list, post such questions on the main "NativeScript" repo

**Comment by PanayotCankov** [comment]
Use algorithms no slower than O(n * log(n)).
