### ISSUE TITLE
tns run android --waiting,wating,waiting...

### ISSUE THREAD

**Issue by 1392324000** [NativeScript/nativescript-marketplace-demo#225]
![demo-err](https://cloud.githubusercontent.com/assets/4407761/18304031/97723f24-7512-11e6-8c91-b3f771ee1db6.png)

After git clone this demo, I am waiting for it's response during the first "tns run android".
This happens after the question"leave your email (press Enter for blank)".
I press Enter ,so,it let me waiting...
Could you help me out from the endless waiting?

**Comment by dtopuzov** [comment]
@1392324000 Is it still valid issue? Can you try to clone master branch again and run:
```
tns install --log trace
````

**Comment by tsonevn** [comment]
Hi @1392324000,

This issue has been related to the using email prompt on postinstall of the `nativescript-telerik-ui` plugin. This problem has been reproduced only on some Windows version and has been reported in [this ](https://github.com/telerik/nativescript-ui-samples/issues/117) issue. The workaround to resolve this problem is to set up an environmental variable called `NSUI_NOPROMPT` and setting its value to `1`. How to set up  environmental variable for Windows could be found [here](http://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt) and [here](http://www.computerhope.com/issues/ch000549.htm).

Regards,
@tsonevn
