### ISSUE TITLE
Demo crashes on first tap.

### ISSUE THREAD

**Issue by fuzeelogik** [NativeScript/nativescript-marketplace-demo#260]
Demo App crashes on ios 10.2

`com.apple.CoreSimulator.SimDevice.295FA018-E85E-4998-93C7-207908CB6D59.launchd_sim[28600] (UIKitApplication:org.nativescript.examples[0x535][30410]): Service exited due to Segmentation fault: 11`

**Comment by NickIliev** [comment]
@fuzeelogik this application is made for demonstration purposes and its published iOS version can be found [here ](https://itunes.apple.com/us/app/examples-nativescript/id1046772499?ls=1&mt=8).

If you want to test the release branch locally and play with the source code then you will need to log in [Firebase console](https://console.firebase.google.com/)  create an application with the same id (org.nativescript.examples) and generate GoogleService0info.plist file in order to enable the Firebase functionality used in the application. The file should replace the existing one in app/App_Resources/iOS and then you should rebuild the application (with deleted **_platforms_** folder) so that the changes can be respected.
